.TH sysloguread.1
.SH NAME
sysloguread \- Read messages from a local domain datagram socket
.SH SYNOPSIS
.B sysloguread
[
.B \-g GID
] [
.B \-u UID
] [
.B \-U
]
.I IP PORT ...
.SH DESCRIPTION
.B sysloguread
opens the named UDP ports for reading.
Every datagram that is sent to the sockets is written to standard
output followed by a newline.
Trailing NUL and newline bytes in the received datagrams are stripped,
but otherwise no data manipulation is done.
An IP of
.I 0
means to bind to all interfaces.
.SH OPTIONS
.TP
.B \-g GID
Switch group ID to GID after preparing to receive connections.
GID must be a positive integer.
.TP
.B \-u UID
Switch user ID to UID after preparing to receive connections.
UID must be a positive integer.
.TP
.B \-U
Same as -g $GID -u $UID.
Typically $GID and $UID are set by
.BR envuidgid .
.SH EXAMPLES
To run this program to securely read syslog messages from
the syslog UDP service (port #514) on all interfaces, use:

.EX
envuidgid nobody syslogread -U 0 514
.EE
.SH SEE ALSO
envuidgid,
sysloglread(1),
syslogxlate(1)
